---
name: push

on:
  push:
    tags: [ '**' ]

jobs:

  call-build-workflow:
    uses: byrdal/docker-nagios/.github/workflows/build.yml@${{ env.GITHUB_REF_NAME }}

  push:
    runs-on: ubuntu-latest
    steps:

      - name: Docker login
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD

      - name: Push image
        run: |
          env | grep GITHUB_REF
          docker tag byrdal/nagios:latest byrdal/nagios:$GITHUB_REF_NAME
          docker push byrdal/nagios:latest
          docker push byrdal/nagios:$GITHUB_REF_NAME
  
